export const fortuneMessages: string[] = [

    // ── English — Mindset ─────────────────────────────────────────────────────
    "Small steps today, big results tomorrow",
    "Patience builds things that luck never can",
    "Not every delay is a loss",
    "You are closer than you feel",
    "Discipline beats motivation every time",
    "Your mindset decides your future",
    "Growth feels uncomfortable for a reason",
    "Consistency is your real power",
    "You don't need perfect timing, just action",
    "Every day is a second chance",
    "Silence often speaks the truth",
    "Learn to wait without losing focus",
    "Energy flows where attention goes",
    "Not everything needs a reaction",
    "Peace is more powerful than proving a point",
    "Your circle shapes your future",
    "Focus on progress, not applause",
    "Slow progress is still progress",
    "You are building something unseen",
    "Hard days create strong people",
    "Don't chase, attract",
    "Respect your own time",
    "Clarity comes from action",
    "You are what you repeat daily",
    "Confidence is built, not gifted",
    "Let your work speak",
    "Stay low, keep growing",
    "Your future self is watching",
    "Not all risks are losses",
    "Choose peace over ego",
    "Be real, not perfect",
    "Keep your standards high",
    "Don't rush what matters",
    "Some losses are lessons",
    "You don't need everyone",
    "Protect your energy",
    "Stay focused on your lane",
    "Win quietly",
    "Not everything deserves your time",
    "Grow in silence",
    "Success is rented, and rent is due daily",
    "You either evolve or repeat",
    "Don't fear starting small",
    "Habits build identity",
    "Your time is limited, use it well",
    "Excuses delay success",
    "Be better than yesterday",
    "Action beats overthinking",
    "Do it even if it's hard",
    "Progress requires sacrifice",
    "Stay humble, stay hungry",
    "Your effort will show",
    "Trust your process",
    "Be consistent, not intense",
    "Think long term",
    "Work now, shine later",
    "Respect the grind",
    "Stay disciplined",
    "Success is quiet",
    "Focus builds results",
    "Not everyone deserves access to you",
    "Choose growth over comfort",
    "Be patient with yourself",
    "Stay grounded",
    "Real growth takes time",
    "You are not behind",
    "Comparison kills progress",
    "Stay in your lane",
    "Your story is different",
    "Keep moving forward",
    "Don't wait for motivation",
    "Be your own push",
    "Stay sharp",
    "Learn from everything",
    "Adapt and grow",
    "You control your direction",
    "Focus on what matters",
    "Cut distractions",
    "Stay committed",
    "Win your day",
    "Strong mind, strong life",
    "Be intentional",
    "Keep your word",
    "Respect discipline",
    "Build your future daily",
    "Keep improving",
    "Think before reacting",
    "Move smart",
    "Stay aware",
    "Good things take time",
    "Stay calm under pressure",
    "You are evolving daily",
    "Don't quit early",
    "Push your limits",
    "Be fearless in effort",
    "Keep your vision clear",
    "Stay positive but realistic",
    "Balance is power",
    "Stay mentally strong",
    "Your habits define you",
    "Protect your peace",
    "Don't waste your energy",
    "Be accountable",
    "Growth is a choice",
    "Be patient",
    "Trust the journey",
    "Keep learning always",
    "Be better daily",
    "You are improving",
    "Keep your goals clear",
    "Move with purpose",
    "You are capable",
    "Keep going",
    "Stay real always",
    "Don't fake growth",
    "Build your own path",
    "Stay original",
    "Think deep",
    "Act smart",
    "Move quietly",
    "Your future needs your effort",
    "Stay hungry for growth",
    "Stay away from negativity",
    "Choose wisely",
    "Act with purpose",
    "Build your mindset",
    "Think ahead",
    "Not all wins are visible",
    "Keep building",
    "You are getting there",
    "Trust your work",
    "Keep pushing forward",
    "Stay calm",
    "Focus on your journey",
    "Every day counts",
    "Use your time wisely",
    "Keep your head clear",
    "Work with purpose",
    "Push yourself",
    "Keep your focus",
    "Stay motivated",
    "Success takes time",
    "You are evolving",
    "Build yourself daily",
    "Stay in control",
    "Keep your energy right",
    "Stay balanced",
    "Keep moving",
    "Keep evolving",
    "One day at a time",
    "Make it count",
    "Show up every day",
    "Results don't lie",
    "Do what others won't",
    "Earn your rest",
    "Stay hungry",
    "Outwork your excuses",
    "Be the hardest worker",
    "Sharpen your focus daily",
    "Your only limit is you",
    "Believe before you achieve",
    "Start before you are ready",
    "Doubt kills more dreams than failure",
    "Make today worth remembering",
    "Silence your doubts with action",
    "The grind never stops",
    "Build habits, not goals",
    "Comfort zones are dream killers",
    "Your decisions shape your destiny",
    "One more rep, one more try",
    "Be relentless",
    "Stay in the fight",
    "Never settle for average",
    "Your effort is your identity",
    "Make sacrifices that matter",
    "Sweat now, shine forever",
    "Do hard things daily",
    "Be uncomfortable on purpose",
    "Upgrade your standards",
    "Own your morning, own your day",
  
    // ── English — Life & Journey ──────────────────────────────────────────────
    "Every journey begins with a single step",
    "The road is long but the destination is worth it",
    "Travel light, think big",
    "Not all who wander are lost",
    "Enjoy the ride, not just the destination",
    "Life is a journey — board it with purpose",
    "New roads bring new lessons",
    "The best views come after the hardest climbs",
    "Every mile teaches something new",
    "A smooth sea never made a skilled sailor",
    "The journey shapes you more than the destination",
    "Keep your eyes on the road ahead",
    "Some detours lead to better places",
    "Arrival is sweet only after the effort",
    "Move forward, even slowly",
    "The path less taken often leads somewhere great",
    "Every stop is a new beginning",
    "Travel with an open mind",
    "Speed matters less than direction",
    "Your next chapter starts now",
  
    // ── English — Relationships & People ─────────────────────────────────────
    "A kind word costs nothing but means everything",
    "Be the reason someone smiles today",
    "Strong people lift others up",
    "Real connections are built on honesty",
    "Listen more than you speak",
    "Family is your greatest wealth",
    "Respect everyone you meet",
    "A true friend is a rare gift",
    "Give without expecting returns",
    "Your kindness is your strength",
    "Help someone today — it costs nothing",
    "Treat others the way you want to be treated",
    "Be someone people can count on",
    "Forgiveness frees you, not just them",
    "Your words can heal or hurt — choose wisely",
    "Build bridges, not walls",
    "Love is shown through actions",
    "Check on your strong friends",
    "A smile is the shortest distance between people",
    "Be present for those who matter",
  
    // ── English — Health & Wellness ───────────────────────────────────────────
    "Your body is your first home — take care of it",
    "Rest is part of the work",
    "Drink water, move your body, rest well",
    "Mental health is real health",
    "Small healthy choices add up to big results",
    "Sleep more, stress less",
    "A walk a day keeps the doctor away",
    "Eat to fuel, not to fill",
    "Your mind needs rest just like your body",
    "Health is the real wealth",
    "Move your body — it was built for motion",
    "One healthy habit at a time",
    "Breathe deeply, think clearly",
    "Stress is a choice — peace is too",
    "Protect your energy like your bank balance",
    "Your body hears everything your mind says",
    "Consistency in health pays compound interest",
    "Invest in rest",
    "Hydrate before you caffeinate",
    "Strong body, clear mind",
  
    // ── Tamil — ஊக்கம் & மனசக்தி ──────────────────────────────────────────────
    "சிறிய அடிகள் பெரிய வெற்றியை உருவாக்கும்",
    "பொறுமை மிகவும் சக்தி வாய்ந்தது",
    "ஒவ்வொரு நாளும் ஒரு புதிய வாய்ப்பு",
    "உன் முயற்சி ஒருநாள் பேசும்",
    "தோல்வி என்பது வெற்றியின் ஆரம்பம்",
    "நீ நினைத்ததை விட நீ வலிமையானவன்",
    "கனவு காண்பவர்கள் மட்டுமே கண்டுபிடிக்கிறார்கள்",
    "உழைப்பை விட வேறு எந்த வழியும் இல்லை",
    "அமைதி என்பது பலவீனம் அல்ல — அது வலிமை",
    "உன்னை நீயே நம்பு",
    "ஒவ்வொரு இரவும் ஒரு புதிய விடியலை கொண்டு வரும்",
    "சவால்கள் உன்னை உடைக்காது — உருவாக்கும்",
    "வெற்றி திடீரென வருவதில்லை — உழைத்தே வரும்",
    "உன் கதை இன்னும் முடியவில்லை",
    "விட்டுவிடாதே — நீ மிகவும் அருகில் இருக்கிறாய்",
    "நேரம் போகிறது — அதை வீணாக்காதே",
    "மனம் தளராதே — வழி கண்டிப்பாக கிடைக்கும்",
    "உன் உழைப்பே உன் அடையாளம்",
    "நம்பிக்கை இருந்தால் சாதிக்கலாம்",
    "ஒவ்வொரு நாளும் சற்றே சிறந்தவனாக ஆவதே வெற்றி",
    "கடின நேரங்கள் உன்னை வடிவமைக்கின்றன",
    "பயம் இருந்தாலும் முன்னேறு",
    "இன்று போட்ட விதை நாளை மரமாகும்",
    "உன் இலக்கை மறவாதே",
    "மற்றவரோடு ஒப்பிட்டுக்கொள்ளாதே",
    "உன்னுடைய பயணம் தனிப்பட்டது",
    "தொடர்ந்து முயற்சி செய் — ஒருவேளை இன்றே திருப்புமுனை",
    "தோற்றாலும் கற்றுக்கொண்டாய்",
    "கவலையை விடு — கவனத்தை வை",
    "வாழ்க்கை ஒரு பாடம் — தொடர்ந்து கற்றுக்கொள்",
    "நீ எங்கிருந்து வந்தாய் என்பதல்ல — எங்கு போகிறாய் என்பதே முக்கியம்",
    "ஒவ்வொரு நிமிடமும் விலைமதிப்பற்றது",
    "விடாமுயற்சி மட்டுமே வெற்றி தரும்",
    "உன் கனவுக்கு நீயே போர்டிடு",
    "சிறியதாக ஆரம்பி — பெரியதாக முடி",
    "இன்று கஷ்டப்படு — நாளை சிரி",
    "ஒழுக்கம் என்பது வெற்றியின் அடிப்படை",
    "உன்னால் முடியும் — அதை உன்னிடமே நிரூபி",
    "ஒவ்வொரு கடினமான நாளும் ஒரு பாடம்",
    "ஒவ்வொரு படியும் உன்னை வலிமைப்படுத்துகிறது",
    "ஓய்வு எடு — ஆனால் விட்டுவிடாதே",
    "உன் மனதை வலிமையாக வை",
    "நேர்மை என்பது உன் மிகப்பெரிய சொத்து",
    "உன்னை நேசி — உனக்கு அது தகும்",
    "சோர்வு தாற்காலிகமானது — பெருமை நிரந்தரமானது",
    "இன்று நீ போட்ட நடவடிக்கை நாளை பலன் தரும்",
    "கனவு கண்டாலே போதாது — ஓடவும் வேண்டும்",
    "வாழ்க்கையை மதிக்க கற்றுக்கொள்",
    "உன் எண்ணங்களே உன் உலகம்",
    "சரியான நேரத்தில் சரியான முயற்சி — வெற்றி நிச்சயம்",
  
    // ── Tamil — வாழ்க்கை & ஞானம் ─────────────────────────────────────────────
    "வாழ்க்கை ஒரு பயணம் — அனுபவித்து செல்",
    "நல்லது செய் — நல்லது வரும்",
    "அன்பு மிகவும் சக்தி வாய்ந்தது",
    "உண்மை என்றும் வெல்லும்",
    "மனிதன் சிறந்தது செய்யும்போது இறைவன் மகிழ்கிறான்",
    "தகுந்த நேரத்தில் தகுந்த செயல் — அதுவே ஞானம்",
    "நன்றி சொல்ல கற்றுக்கொள்",
    "மரியாதையோடு வாழ்",
    "சிறியவர்களிடம் பெரிய மனசு வை",
    "வார்த்தைகள் கத்தியை விட கூர்மையானவை — கவனமாக பேசு",
    "உன் நேரத்தை மதி",
    "அடுத்தவரோடு ஒப்பிட்டு வாழாதே",
    "நல்ல நண்பன் ஆயிரம் செல்வம்",
    "பொய் கொஞ்ச நாள் — உண்மை என்றும்",
    "அமைதியாக இரு — வெற்றி தானே வரும்",
    "சின்ன உதவியும் பெரிய மாற்றம் தரும்",
    "மனசு தெளிவாக இருந்தால் வழி தெரியும்",
    "பொறுமை இருந்தால் எதுவும் சாத்தியம்",
    "கவலை வேண்டாம் — கடவுள் உன்னோடு இருக்கிறார்",
    "ஒவ்வொரு பிரச்சினைக்கும் ஒரு தீர்வு இருக்கும்",
    "நன்மை செய்தால் நன்மை வரும் — காலம் வரை காத்திரு",
    "வாழ்க்கையில் எந்த நேரமும் கற்றுக்கொள்ளலாம்",
    "குடும்பமே கோட்டை",
    "உறவுகளை மதி — பணத்தை விட உறவு மேலானது",
    "ஒவ்வொரு சந்திப்பும் ஒரு பாடம்",
    "வாழ்க்கை கொடுப்பதை ஏற்று — மாற்ற முயற்சி செய்",
    "சந்தோஷம் உன்னிடமே இருக்கிறது — தேடு",
    "மனிதாபிமானம் மிக முக்கியம்",
    "உதவி கேட்பது பலவீனம் அல்ல — அது துணிச்சல்",
    "ஒரு நல்ல சிரிப்பு மனதை குணப்படுத்தும்",
  
    // ── Tamil — ஆரோக்கியம் ────────────────────────────────────────────────────
    "உடல் நலம் மிகவும் அவசியம்",
    "தினமும் நடை பயிற்சி செய்",
    "சரியாக தூங்கு — உடல் புத்துணர்வு பெறும்",
    "நீர் அருந்துவது மிகவும் முக்கியம்",
    "மனம் அமைதியாக இருந்தால் உடல் ஆரோக்கியமாக இருக்கும்",
    "கோபத்தை கட்டுப்படுத்து — அது உன் உடலை அழிக்கும்",
    "சாப்பிடும்போது கவனமாக சாப்பிடு",
    "ஓய்வும் உழைப்பின் ஒரு பகுதி",
    "மன அழுத்தத்தை குறை — வாழ்க்கை நீளமாக இருக்கும்",
    "உன் உடலை நேசி — அது உன்னை நேசிக்கும்",
  
    // ── Tamil — உறவுகள் & மனிதர்கள் ─────────────────────────────────────────
    "அன்பானவர்களுக்கு நேரம் கொடு",
    "பெற்றோரை மதி — அவர்கள் உன் வேர்",
    "நண்பனுக்கு நல்லதே நினை",
    "அடுத்தவர் மனதை புரிந்துகொள்",
    "சின்ன அக்கறை உறவை வலுப்படுத்தும்",
    "உன்னிடம் வரும் ஆள் ஏதோ ஒரு காரணத்திற்காக வருகிறார்",
    "அன்பு செய் — திரும்பவும் கிடைக்கும்",
    "மனிதர்கள் தவறு செய்வார்கள் — மன்னிக்க கற்றுக்கொள்",
    "கேட்கவும் கற்றுக்கொள் — பேசுவது மட்டும் அல்ல",
    "ஒவ்வொரு மனிதனிடமும் ஒரு கதை இருக்கும்",
  
    // ── Mixed Tamil+English (Tanglish style) ────────────────────────────────
    "Daily effort-ஐ விட வேறு shortcut இல்லை",
    "உன் dream-க்கு உன்னோட work ethic match ஆகணும்",
    "Comfort zone-ல இருந்தா growth இல்லை",
    "Hard work எப்பவும் pay off ஆகும் — trust the process",
    "உன் potential-ஐ waste பண்ணாதே",
    "Focus இருந்தா எந்த goal-உம் possible",
    "Progress slow-ஆ இருந்தாலும் — progress தான்",
    "Every setback is a setup for a comeback",
    "உன் story-ல நீயே hero — remember that",
    "Small wins-ஐ celebrate பண்ணு — அது உன்னை முன்னேற்றும்",
    "Bad days are temporary — your strength is permanent",
    "உன் எதிர்காலம் உன் கைல இருக்கு",
    "Consistency + patience = success",
    "உன் competition நீயே — yesterday's version",
    "Failure is feedback — learn and move on",
    "உன் journey-ல இருக்கற obstacles — உன்னை shape பண்றது",
    "Think big, start small, move fast",
    "உன் time வரும் — ready-ஆ இரு",
    "Show up even when you don't feel like it",
    "உன் habits-ஐ change பண்ணு — life change ஆகும்",
    "வலி தாத்காலிகமானது — victory நிரந்தரமானது",
    "Invest in yourself — best ROI ever",
    "உன் mind-ஐ train பண்ணு — body follow ஆகும்",
    "Done is better than perfect",
    "Work in silence — let success make the noise",
    "உன் attitude-ஐ check பண்ணு — அதுவே உன் altitude",
    "Every master was once a disaster",
    "உன் கனவு பெரியதா இருந்தாலும் — effort அதை விட பெரியதா இரு",
    "Be a student forever",
    "உன் வாழ்க்கை உன் choices-ஓட result",
    "Push through the resistance",
    "Plan பண்ணு, execute பண்ணு, adjust பண்ணு",
    "உன் worth-ஐ தெரிஞ்சுக்கோ",
    "Stay hungry, stay foolish",
    "உன்னோட உழைப்பு ஒருநாள் நீ நினைக்காத இடத்தில் வச்சிடும்",
    "Be the energy you want to attract",
    "உன் boundaries-ஐ protect பண்ணு",
    "Good things take time — don't rush",
    "உன் passion-ஐ follow பண்ணு, money follow ஆகும்",
    "Level up daily",
    "உன் mind-ஐ positive-ஆ வை — life positive-ஆ மாறும்",
    "Less talk, more action",
    "உன் growth-ஐ others-கிட்ட explain பண்ண வேண்டாம்",
    "Success is a journey, not a destination",
    "உன் day-ஐ design பண்ணு — waste பண்ணாதே",
    "Discipline is the bridge between goals and accomplishment",
    "உன் excuses-ஐ உன் motivation-ஆ மாத்து",
    "Take action — one step at a time",
    "உன் future-க்காக இன்று sacrifice பண்ணு",
    "Build the life you want, one habit at a time",
  
    // ── More English — Deep Wisdom ────────────────────────────────────────────
    "The quieter you become, the more you can hear",
    "Fall seven times, stand up eight",
    "It always seems impossible until it is done",
    "Don't count the days, make the days count",
    "A year from now you will wish you had started today",
    "You miss 100% of the shots you don't take",
    "The secret is to get started",
    "What you do today can improve all your tomorrows",
    "Tough times never last, but tough people do",
    "The only way out is through",
    "Believe you can and you're halfway there",
    "Do what you can with what you have where you are",
    "You are enough — exactly as you are",
    "Make each day your masterpiece",
    "Dream big, work hard, stay humble",
    "The best time to plant a tree was 20 years ago. The second best time is now",
    "Your life does not get better by chance — it gets better by change",
    "Stars can't shine without darkness",
    "Don't let yesterday take up too much of today",
    "Be so good they can't ignore you",
    "You have survived 100% of your worst days",
    "In the middle of difficulty lies opportunity",
    "Strength doesn't come from what you can do — it comes from overcoming what you once couldn't",
    "The harder you work for something, the greater you'll feel when you achieve it",
    "It's not about perfect — it's about effort",
    "Your current situation is not your final destination",
    "Don't wish it were easier — wish you were better",
    "The pain you feel today will be the strength you feel tomorrow",
    "Live as if you were to die tomorrow, learn as if you were to live forever",
    "Happiness is not something ready made — it comes from your own actions",
    "When you feel like quitting, think about why you started",
    "Do something today that your future self will thank you for",
    "It does not matter how slowly you go as long as you do not stop",
    "Success is not final, failure is not fatal — it is the courage to continue",
    "Wake up with determination, go to bed with satisfaction",
    "Be the change you want to see in the world",
    "Stop waiting for Friday, for summer, for someone to fall in love with you",
    "You don't have to be great to start, but you have to start to be great",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us",
    "Act as if what you do makes a difference — it does",
  
    // ── More Tamil Wisdom ─────────────────────────────────────────────────────
    "கற்றது கைமண் அளவு — கல்லாதது உலகளவு",
    "ஆயிரம் தவறுகள் செய்தாலும் — ஒரு தவறிலிருந்து கற்றால் போதும்",
    "வெற்றி என்பது எழுந்திருக்கும் எண்ணிக்கை",
    "நன்றி மறவாமை — அதுவே மனித தர்மம்",
    "சிறு துளி பெரு வெள்ளம்",
    "அன்னையும் பிதாவும் முன்னறி தெய்வம்",
    "இன்னா செய்தாரை ஒறுத்தல் — அவர் நாண நன்னயம் செய்து விடல்",
    "யாகாவாராயினும் நாகாக்க — காவாக்கால் சோகாப்பர் சொல்",
    "அகர முதல எழுத்தெல்லாம் — ஆதி பகவன் முதற்றே உலகு",
    "வினைத்தூய்மை நீங்கா — வாழ்வு",
    "கனவு கண்டவன் — கண்ணீர் தோய்ந்தே கண்டான்",
    "உழவே தொழிலா — மண்ணே மனமா",
    "வாழ்வும் மாயம் — வழியும் மாயம் — ஆயினும் உழைப்பு உண்மை",
    "நல்லதை நினை — நல்லதே வரும்",
    "தாயின் அன்பிற்கு ஈடு எதுவுமில்லை",
    "மழையில் நனையாமல் வானவில் காண முடியாது",
    "கல் தோன்றி மண் தோன்றா — காலத்தே முன் தோன்றிய மூத்தகுடி தமிழர்",
    "ஒற்றுமையே வலிமை",
    "செய்யும் தொழிலே தெய்வம்",
    "நேர்மையாக உழை — நாளை நல்லதாகும்",
    "ஊருக்கு உதவி செய் — உலகம் உனக்கு உதவும்",
    "இந்த நிமிடம் உன்னுடையது — வீணாக்காதே",
    "படித்தால் மட்டும் போதாது — புரிந்துகொள்ள வேண்டும்",
    "தமிழர் என்பதில் பெருமை கொள்",
    "வீரம் என்பது பயமின்மை அல்ல — பயத்தோடு முன்னேறுவது",
    "துணிவே வெற்றியின் முதல் படி",
    "ஒவ்வொரு மனிதனுக்கும் ஒரு தினம் வரும்",
    "சோர்வு தோல்வி அல்ல — விடுவதே தோல்வி",
    "மனம் உறுதியாக இருந்தால் மலையும் வெல்லலாம்",
    "இன்று செய்வதை நாளைக்கு போடாதே",
  
  ];
  
  export const getRandomFortune = (): string => {
    const index = Math.floor(Math.random() * fortuneMessages.length);
    return fortuneMessages[index];
  };